export const LOGGIN_LOADING = 'LOGGIN_LOADING';
export const SET_LOGGEDIN = 'SET_LOGGEDIN';
export const LOGGIN_FAILED = 'LOGGIN_FAILED';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCES = 'REGISTER_SUCCES';
export const REGISTER_FAILED = 'REGISTER_FAILED';

//ACCIONTES PARA LAS TAREAS
export const ADD_TAREA = 'ADD_TAREA';
export const ADD_TAREAS = 'ADD_TAREAS';
export const NEW_TAREA = 'NEW_TAREA';
export const EDIT_TAREA = 'EDIT_TAREA';
export const SEND_TAREA = 'SEND_TAREA';
export const DELETE_TAREA = 'DELETE TAREA';
export const TAREA_LOADING = 'TAREA_LOADING';
export const TAREA_FAILED = 'TAREA_FAILED'
export const TAREA_SELECTED = 'TAREA_SELECTED';